BEGIN TRANSACTION;
insert into [dbo].[Values] (Name , Type) VALUES ('CSR Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('Fee Based Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('Finance Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('IISC Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('Legal Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('LRT Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('Marketing Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('Non PMKVY Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('Standards Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('PMKVY STT Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('PMKVY RPL Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('PMKVY SP Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('PMKVY Monitoring Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('States Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('TOT & TOA Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('SSC Governance Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('IT Team','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('Technical Vendor','dept');
insert into [dbo].[Values] (Name , Type) VALUES ('admin','role');
insert into [dbo].[Values] (Name , Type) VALUES ('requester','role');
insert into [dbo].[Values] (Name , Type) VALUES ('dev','role');
insert into [dbo].[Values] (Name , Type) VALUES ('it','role');
insert into [dbo].[Values] (Name , Type) VALUES ('uat','role');
insert into [dbo].[Values] (Name , Type) VALUES ('it','role');
COMMIT;
